services:
  - type: web
    name: smartgate-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DB_SCHEMA
        value: public
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: CAMERA_INDEX
        value: 0
      - key: DETECTIONS_LOG
        value: 0
      - key: MODELS_DIR
        value: models
